language: c
os: linux
sudo: false
compiler:
  - gcc
  - clang
env:
  - ZFS=

script:
   - ( cd buildrump.sh && ./buildrump.sh -s ../src-netbsd -V MKSTATICLIB=no -qq fullbuild )
   - ./buildnb.sh -qq ${ZFS} tests ./buildrump.sh/rump

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - bad@bsd.de
    on_success: always
    on_failure: always
